# Generated by Django 2.1.2 on 2019-02-04 17:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20181103_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 17, 56, 13, 247379, tzinfo=utc)),
        ),
    ]
