# Generated by Django 2.1.2 on 2019-04-03 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190204_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 3, 5, 13, 27, 405773, tzinfo=utc)),
        ),
    ]
